version: '3'

services:
  nginx:
    image: liransehayk/my-nginx:latest
    ports:
      - "8080:80"
    networks:
      - devops_test
    deploy:
      mode: replicated
      replicas: 1
      
networks:
  devops_test:
    driver: overlay